spring:
  application:
    name: CONFIG-DEFAULT
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8087/eureka
  instance:
    prefer-ip-address: true
